# Generated by Django 3.2.13 on 2022-06-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookresult',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookresult',
            name='hunger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookresult',
            name='mentality',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etcingredient',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fruitingredient',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meatingredient',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meatingredient',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seafoodingredient',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vegetableingredient',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
